declare type Label = {
  color: string,
  default: boolean,
  id: number,
  name: string,
  url: string,
};

declare type Issue = {
  id: number,
  body: string,
  assignee: any,
  assignees: any[],
  closed_at: string,
  comments: number,
  comments_url: string,
  created_at: string,
  events_url: string,
  html_url: string,
  labels: Label[],
  labels_url: string,
  locked: boolean,
  milestone: number,
  number: number,
  repository_url: string,
  state: 'open'|'closed',
  title: string,
  updated_at: string,
  url: string,
  user: User,
};
